---
# VMWARE 
# vSphere and VMs
#
username: "root"
password: "vmware"
newvmname: "NS-MUT"
vmname: "NS-CODENOMICONE-TARGET"
template: "ns-template"
template_vm: "Scratchy"
template_centos6: tmp_cent6
template_centos7: tmp_cent7
template_win2008: tmp_win2008
template_win2012: tmp_win2012
template_solaris: tmp_solaris
template_ubuntu_: tmp_ubuntu
vms_datastore: ns_fc_m1
resource_pool: "/Resources"
cluster: "foo"
datacenter: "KRD"
mut_datastor: "ns-1"
vcenter_hostname: "10.3.70.131"
esxname: "10.3.70.29"
esxname2: "10.3.70.16"
osid: "solaris10_64Guest"
mac1: "00:50:56:aa:29:ba"
vm_folder: "MUTS"
vmnet: "VM Network"
vmnet2: "VM Network 2"
note: "IO Drones for LargeHA"
# VMs count
default_count: 0
cent6: "{{default_count}}"
cent7: "{{default_count}}"
cent6mix: "{{default_count}}"
cent7mix: "{{default_count}}"
cent6local: "{{default_count}}"
cent7local: "{{default_count}}"
ubuntunfs: "{{default_count}}"
ubuntucifs: "{{default_count}}"
ubuntumix: "{{default_count}}"
ubuntulocal: "{{default_count}}"
win2008: "{{default_count}}"
win2012: "{{default_count}}"
# other
nameserver: "192.168.1.150"

# VDBENCH
#Configs
vdbench_config: "vdb.conf"
vdbench_config_mix_nfs: "vdb_mix_nfs.conf"
vdbench_config_mix_cifs: "vdb_mix_cifs.conf"
vdbench_config_tmp: "templates/vdb.conf.j2"
# fio
fioconf: "fio.conf"
fiotmp: "roles/common/templates/fio.conf.j2"

#Archives
vdbench_zip: "files/vdb.zip"
vdbench_targz: "files/vdb.tar.gz"

# Pathes
root_path: "/root"
root_win_path: "/home/root"
vdb_folder_path: "{{ root_path }}/VDBench"
vdb_folder_win_path: "{{ vdb_folder_win_path }}/VDBench"
dstpathwin: "/cygdrive/x"
#
vd_target_nfs: "{{ vdb_folder_path  }}/fsload"
vd_target_cifs: "{{ vdb_folder_path }}/fsload2"
vd_target_local: "{{ vvdb_folder_path }}/fsload3"

#Scripts
vdbshell: "vdbench.bash"
vdbbat: "vdbench.bat"

#IPs
vip1: "192.168.1.1"
vip2: "192.168.1.2"
vip3: "192.168.1.3"
share_ip: "{{ vip2 }}"

#SHARES and POOLS
mountpoint: "/"
pool1: "tankm1"
pool2: "tankz2"
pool3: "tank8"
pool_for_shares: "{{ pool1 }}"

#CIFS Optiona
cifs_user: "smb"
cifs_passwd: "nexenta"
cifs_share: "{{ pool_for_shares }}_cifs_cifs-"

#NFS
nfs_share: "{{ mountpoint }}{{ pool_for_shares }}/nfs/nfs-"

#MIX CIFS and NFS
mix_nfs_share: "{{ mountpoint }}{{ pool_for_shares }}/mix/mix-"
mix_cifs_share: "{{ pool_for_shares }}_mix_mix-"

#Trash
kek: "./VDBench/"

#vdbench configuration vars

anchor: "{{ vd_target_nfs }}"
width: 4
depth: 4
files: 50
size: 512k
