---
#VMWARE vSphere
username: "root"
password: "vmware"
newvmname: "NS-MUT"
vmname: "NS-CODENOMICONE-TARGET"
template: "ns-template"
template_vm: "Scratchy"
template_centos6: tmp_cent6
template_centos7: tmp_cent7
template_windows2008: tmp_win2008
template_windows2012: tmp_win2012
template_solaris: tmp_solaris
resource_pool: "/Resources"
cluster: "foo"
datacenter: "KRD"
mut_datastor: "ns-1"
vcenter_hostname: "10.3.70.131"
esxname: "10.3.70.29"
esxname2: "10.3.70.16"
osid: "solaris10_64Guest"
mac1: "00:50:56:aa:29:ba"
vm_folder: "MUTS"
vmnet: "VM Network"
vmnet2: "VM Network 2"
note: "IO Drones for LargeHA"
# other
nameserver: "192.168.1.150"

#Confs
vconf: "vdb.conf"
fioconf: "fio.conf"
fiotmp: "roles/common/templates/fio.conf.j2"
vconftmp-1: "roles/common/templates/vdb.conf.j2"
vconftmp2-1: "roles/common/templates/vdb.conf2.j2"
#small
vconftmp: "roles/common/templates/vdb.conf.j2"
vconftmp2: "roles/common/templates/vdb2.conf2.j2"
vconftmp3: "roles/common/templates/vdb2.conf3.j2"


#Archives
vdarchz: "roles/common/files/vdb.zip"
vdarcht: "roles/common/files/vdb.tar.gz"

# Pathes
vdpath: "/root/VDBench/"
vdpathw: "/home/root/VDBench/"
dstpath: "/root/"
dstpathwin: "/cygdrive/x/"

#Scripts
vdbshell: "vdbench.bash"
vdbbat: "vdbench.bat"

#IPs
vip1: "192.168.1.1"
vip2: "192.168.1.2"
vip3: "192.168.1.3"

#Shares
nfs1: "/volumes/tankm1/nfs/nfs-"
nfs2: "/volumes/tankz2/nfs/nfs-"
nfs3: "/volumes/tank8/nfs/nfs-"
cifs: "tankz2_cifs_cifs-"
mixnfs: "/volumes/tankz2/mix/mix-"
mixcifs: "tankz2_mix_mix-"

#
testvolume: "kek"
kek: "./VDBench/"

#Vsphere


