---
- include_vars: "{{ vars_file }}"
- assert:
   that:
    - vconf != ""
    - vdarcht != ""
    - vdpath != ""
    - vdbshell != ""
- name: Configure resolvconf
  lineinfile: dest=/etc/resolv.conf line='nameserver 8.8.8.8'
#- include: apt.yml
#  when: ansible_pkg_mgr == 'apt'
#- include: yum.yml
#  when: ansible_pkg_mgr == 'yum'
#- name: UUUMount share (NFS) shell all
#  shell: umount -a
#  ignore_errors: yes
#- name: UUUMount share (NFS) shell fsload try 2
#  shell: umount -f -l /root/VDBench/fsload
#  ignore_errors: yes
#- name: UUUMount share (CIFS) shell VDB
#  shell: umount -f -l /root/VDBench
#  ignore_errors: yes
- name: Delete THE Folder log
  file: path=/root/output state=absent mode=0777
  ignore_errors: yes
- name: Delete THE Folder log2
  file: path=/root/output2 state=absent mode=0777
  ignore_errors: yes
- name: Create THE Folder
  file: path="{{vdpath}}" state=directory mode=0777
- name: Create THE Folder
  file: path=/root/fsload state=directory mode=0777

- name: Copy config local
  template: src={{vconftmp3}} dest="{{vdpath}}{{vconf}}2"
- name: Unzip vdb to folder
  unarchive: src={{vdarcht}} dest="{{vdpath}}"
- name: Run IO local
  shell: "{{vdpath}}{{vdbshell}} -f {{vdpath}}{{vconf}}2 -o /root/output2"
  async: 4000000
  poll: 0



