---
# tasks file for vdbench
- include_vars: "{{ vars_file }}"
- assert:
   that:
    - vconf != ""
    - vdarcht != ""
    - vdpath != ""
    - vdbshell != ""
- name: Configure resolvconf
  lineinfile: dest=/etc/resolv.conf line='nameserver 8.8.8.8'
- name: Configure apt
  lineinfile:
    dest: /etc/apt/sources.list
    line: "{{ item.line }}"
  with_items:
    - { line: 'deb http://apt.nexenta.com/nza4/community base-stable/4.0 main contrib non-free' }
    - { line: 'deb http://apt.nexenta.com/nza4/community kernel-stable/4.0 main contrib non-free' }
    - { line: 'deb http://apt.nexenta.com/nza4/community nza-stable/4.0 main contrib non-free' }
    - { line: 'deb http://apt.nexenta.com/nza4/community plugins-stable/4.0 main contrib non-free' }
- name: Install packages
  command: apt-get update
- name: Install packages
  command: apt-get install compress-unzip runtime-java shell-tcsh -y
- name: Create THE Folder
  file: path={{ vdpath }} state=directory mode=0777
- name: Copy config
  template: src=../../common/templates/{{ vconf }}.j2 dest={{ vdpath }}{{ vconf }}
- name: Unzip vdb to folder
  unarchive: src={{vdarcht}} dest={{ vdpath }}
- name: Run IO
  shell: "{{ vdpath }}{{ vdbshell }} -f {{ vdpath }}{{ vconf }}"
  async: 4000000
  poll: 0
